[font]
size = 14.0

[font.bold]
family = "JetBrainsMono Nerd Font"
style = "Bold"

[font.bold_italic]
family = "JetBrainsMono Nerd Font"
style = "Bold Italic"

[font.italic]
family = "JetBrainsMono Nerd Font"
style = "Italic"

[font.normal]
family = "JetBrainsMono Nerd Font"
style = "Bold"

[font.offset]
x = 1
y = 1

[scrolling]
history = 100000

[window]
title = "i'm @ you're @"
opacity = 0.9
padding = { x = 0, y = 0 }

[env]
TERM = "xterm-256color"

[general]
import = [
  "~/.config/alacritty/nord.toml"
]

[terminal]
shell = "/bin/zsh"

[window.class]
general = "Alacritty"
instance = "Alacritty"
